//CUSTOMER
const CUSTOMER = "customer";
const CUSTOMER_ADDRESS = `${CUSTOMER}/address`;
const CUSTOMER_ADDRESS_DEFAULT = `${CUSTOMER_ADDRESS}/default`;
const CUSTOMER_ADDRESS_PROVINCE = `${CUSTOMER_ADDRESS}/province`;
const CUSTOMER_ADDRESS_CITY = `${CUSTOMER_ADDRESS}/city`;
const CUSTOMER_ADDRESS_SUBDISTRICT = `${CUSTOMER_ADDRESS}/subdistrict`;
const CUSTOMER_ADDRESS_DELETE = `${CUSTOMER_ADDRESS}/`
const CUSTOMER_UPLOAD_IMAGE = 'image/upload-image'
const CUSTOMER_UPLOAD = 'image/upload'
export const PATH_CUSTOMER = {
    CUSTOMER_ADDRESS_DELETE : CUSTOMER_ADDRESS_DELETE,
    CUSTOMER : CUSTOMER,
    ADDRESS_DEFAULT: CUSTOMER_ADDRESS_DEFAULT,
    ADDRESS: CUSTOMER_ADDRESS,
    ADDRESS_PROVINCE: CUSTOMER_ADDRESS_PROVINCE,
    ADDRESS_CITY: CUSTOMER_ADDRESS_CITY,
    ADDRESS_SUBDISTRICT: CUSTOMER_ADDRESS_SUBDISTRICT,
    CUSTOMER_UPLOAD: CUSTOMER_UPLOAD,
    CUSTOMER_UPLOAD_IMAGE : CUSTOMER_UPLOAD_IMAGE
}