//PUBLIC
const PUBLIC_USER_LOGIN = "public/user/login";
const PUBLIC_USER_REGISTER = "public/user/register";
const PUBLIC_USER_ACTIVED = "public/user/actived";
const PUBLIC_FORGOT_PASSWORD = "password/forgot";
const PUBLIC_CHANGE_PASSWORD = "password/change";
const PUBLIC_RESET_PASSWORD = "password/reset";
const PUBLIC_OAUTH_SOSIAL_MEDIA_GOOGLE = "public/oauth/sosial-media/google";
const PUBLIC_OAUTH_SOSIAL_MEDIA_FACEBOOK = "public/oauth/sosial-media/facebook";
const PUBLIC_USER_RESEND_VERIFICATION = "public/user/resend/verification";
export const PATH_PUBLIC = {
    PUBLIC_USER_LOGIN: PUBLIC_USER_LOGIN,
    PUBLIC_USER_REGISTER: PUBLIC_USER_REGISTER,
    PUBLIC_USER_ACTIVED: PUBLIC_USER_ACTIVED,
    PUBLIC_FORGOT_PASSWORD: PUBLIC_FORGOT_PASSWORD,
    PUBLIC_CHANGE_PASSWORD: PUBLIC_CHANGE_PASSWORD,
    PUBLIC_RESET_PASSWORD: PUBLIC_RESET_PASSWORD,
    PUBLIC_OAUTH_SOSIAL_MEDIA_GOOGLE: PUBLIC_OAUTH_SOSIAL_MEDIA_GOOGLE,
    PUBLIC_OAUTH_SOSIAL_MEDIA_FACEBOOK: PUBLIC_OAUTH_SOSIAL_MEDIA_FACEBOOK,
    PUBLIC_USER_RESEND_VERIFICATION : PUBLIC_USER_RESEND_VERIFICATION
} 